spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:xxx}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
      chat:
        # 启用OpenAI聊天模型
        enabled: true
        options:
          # 默认使用的模型
          model: ${OPENAI_MODEL:gpt-4o}
          # 默认温度参数 (1.0.0-M6版本使用Double类型)
          temperature: 0.7
          # 默认最大token数
          max-tokens: 2000
    deepseek:
      api-key: ${DEEPSEEK_API_KEY:xxx}
      base-url: ${DEEPSEEK_BASE_URL:https://api.deepseek.com}
      chat:
        # 启用OpenAI聊天模型
        enabled: true
        options:
          # 默认使用的模型
          model: ${DEEPSEEK_MODEL:deepseek-chat}
          # 默认温度参数 (1.0.0-M6版本使用Double类型)
          temperature: 0.7
          # 默认最大token数
          max-tokens: 5000

getjobs:
  ai:
    prompts:
      job:
        match-position:
          description: 基于候选人目标职责与职位描述判断是否匹配
          placeholders:
            - my_jd
            - jd
          template: |-
            帮我根据职位描述判断对应职位是否匹配我的岗位，我需要做
            {my_jd}
            工作，给我返回是否匹配即可，是返回true，否返回false

            职位描述如下：
            {jd}

